# CI documents: https://docs.platformio.org/en/latest/integration/ci/github-actions.html#integration
name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [ ./examples/face-and-color/face-and-color.ino]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
                ~/.cache/pip
                ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v5
      with:
          python-version: '3.11'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    - name: Build PlatformIO examples
      run: pio ci --project-option="lib_deps=M5Unified" --board=m5stack-core-esp32  -l ./src
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}